### PR TITLE
create note code

### PR DESCRIPTION
**Pull request by Lisonallie**
Here I am submitting my code I've created to CREATE a note in my database API. I've added helpful comments explaining what's happening along the way and tried to give my variables names that make semantic sense.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
I've reviewed your code and it seems pretty good so far :). I'm kind of confused to why you would want to echo the errors in a json-format. Also on the end of your script you could close connection using ```$conn->close();```

**Comment by Lisonallie** [comment]
> I've reviewed your code and it seems pretty good so far :). I'm kind of confused to why you would want to echo the errors in a json-format. Also on the end of your script you could close connection using `$conn->close();`
Hi Jan, I echoed the json errors so the response the user receives is JSON which was the assignment. I'm not 1000% sure if it's the right way, but this is the way I found for this.
Thank you, I have added this!

**Comment by WietseGielen** [comment]
Your code looks good and your way of displaying the errors in JSON looks simplier and better than the way I've found. 

If `$feedback['fail'] = "you've some errors";` don't work you can try `$feedback = [ "fail" => "you've some errors" ];`

**Comment by Lisonallie** [comment]
> Your code looks good and your way of displaying the errors in JSON looks simplier and better than the way I've found.
> 
> If `$feedback['fail'] = "you've some errors";` don't work you can try `$feedback = [ "fail" => "you've some errors" ];`
Hi Wietse, thanks for the helpful feedback an alternative method! I'd be interested to see the way you found all the same.

**Pull request merged**
